# Prefer using `SourcePos` from because it abstracts
# away swc's non-zero-indexed based positioning
disallowed-methods = [
  "swc_common::Spanned::span",
]
disallowed-types = [
  "swc_common::BytePos",
  "swc_common::Span",
  "swc_common::Spanned",
]
