name: publish

on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: 'Kind of release'
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
        required: true

jobs:
  rust:
    name: deno_ast-ubuntu-latest-publish
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
      - uses: dtolnay/rust-toolchain@stable

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.DENOBOT_PAT }}
          GH_WORKFLOW_ACTOR: ${{ github.actor }}
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          deno run -A https://raw.githubusercontent.com/denoland/automation/0.14.0/tasks/publish_release.ts --${{github.event.inputs.releaseKind}}
